### ISSUE TITLE
Clean up multiple environments

### ISSUE THREAD

**Issue by cosunae** [mizeller/pytrajplot#23]
* pytrajplot version:
* Python version:
* Operating System:

### Description

Right now the situation with the strategy with environment is not very clear or clean. In https://github.com/MeteoSwiss-APN/pytrajplot/pull/21 we introduced a new environment file, in addition to the existing ones, just for github actions. 
We should try to follow the same strategy as the blueprint,

**Comment by Karko93** [comment]
Done. Removed Redundant Environments.
