### ISSUE TITLE
Update code to eliminate runtime "future warnings"

### ISSUE THREAD

**Issue by pirmink** [mizeller/pytrajplot#25]
* pytrajplot version: 1.1.2

### Description

Update the souce code to fulfill future requirements announced as runtime "future warings":

    /scratch/jenkins/workspace/DispersionModel_pytrajplot_PR-18/miniconda/envs/dev_env/lib/python3.9/site-packages/pytrajplot/generate_pdf.py:526: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.

      pd.Series(),

    /scratch/jenkins/workspace/DispersionModel_pytrajplot_PR-18/miniconda/envs/dev_env/lib/python3.9/site-packages/pytrajplot/generate_pdf.py:527: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.

      pd.Series(),

    /scratch/jenkins/workspace/DispersionModel_pytrajplot_PR-18/miniconda/envs/dev_env/lib/python3.9/site-packages/pytrajplot/generate_pdf.py:717: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

      trajectory_latitude_expansion = trajectory_latitude_expansion.append(

    /scratch/jenkins/workspace/DispersionModel_pytrajplot_PR-18/miniconda/envs/dev_env/lib/python3.9/site-packages/pytrajplot/generate_pdf.py:720: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

      trajectory_longitude_expansion = trajectory_longitude_expansion.append(

    /scratch/jenkins/workspace/DispersionModel_pytrajplot_PR-18/miniconda/envs/dev_env/lib/python3.9/site-packages/pytrajplot/generate_pdf.py:782: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.

      pd.Series(),

    /scratch/jenkins/workspace/DispersionModel_pytrajplot_PR-18/miniconda/envs/dev_env/lib/python3.9/site-packages/pytrajplot/generate_pdf.py:783: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.

      pd.Series(),

**Comment by Karko93** [comment]
Done.
